---
fullname: Robbins
shortname: robbins
organization: thery
community: false
dune: false
action: true

synopsis: All Robbins algebras are Boolean algebras

description: |-
  All Robbins algebras are Boolean algebras

  A transcription in Coq of : `A Complete Proof of the Robbins Conjecture` 
  Allen L. Mann  

authors:
- name: Laurent Théry

maintainers:
- name: Laurent Théry
  nickname: thery

opam-file-maintainer: thery@sophia.inria.fr

license:
  fullname: MIT License
  identifier: MIT

supported_coq_versions:
  text: '8.18 or later'
  opam: '{(>= "8.18")}'

dependencies:
- opam:
    name: coq-mathcomp-ssreflect
    version: '{(>= "2.1.0")}'
  description: |-
    [MathComp ssreflect 2.1 or later](https://math-comp.github.io)

tested_coq_opam_versions:
- version: '2.1.0-coq-8.18'
  repo: 'mathcomp/mathcomp'

namespace: robbins

keywords:
- name: robbins
- name: boolean algebra


---